### ISSUE TITLE
Luminance Curve tool should be a "general" parameter ?

### ISSUE THREAD

**Issue by eloimaduell** [PlaymodesStudio/MIRABCN_Generator#24]
It's working perfectly ! But I guess it should be placed on the "general" parameter group ... As it will affect the main output ?

**Comment by eloimaduell** [comment]
And maybe ... "show curve" might be better then "Draw Curve" ?

**Comment by eloimaduell** [comment]
And ... it should be possible to save it as a "config" thing ... we would like to be able to save it ...

**Comment by eduardfrigola** [comment]
Wave2D is in charge of distributing the diferent oscillators in the last fbo, and for this reasor it controls this parameter.
A better way will be to have another class that does this functionality, and then this class will have all those parameters.

Also the curve is stored in "responsecurve.yml" on exit. And loaded on startup
